name: xeus-octave
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  # Host dependencies
  - xeus >= 2.0
  - xwidgets
  - xproperty
  - nlohmann_json
  - cppzmq
  - xtl
  - octave
  - jupyterlab
  - mesa-libgl-devel-cos7-x86_64
  #- glfw
  - xorg-libx11            # [linux]
  - xorg-libxrandr         # [linux]
  - xorg-libxinerama       # [linux]
  - xorg-libxcursor        # [linux]
  - xorg-libxi             # [linux]
  - xorg-libxrandr         # [linux]
  - xorg-libxcursor        # [linux]
  # Test dependencies
  - pytest
  - jupyter_kernel_test>=0.4.3
  - nbval
  - pytest-rerunfailures